/* eslint-disable */
const dsgcBaseUrl = 'centers/data-and-signature-generating-centers';

export default [
  {
    name: 'BD2K-LINCS DCIC',
    internalLink: 'centers/dcic',
    url: 'http://lincs-dcic.org/',
    iconUrl: 'http://lincsproject.org/LINCS/files/centers_logos/DCIC.svg',
    description: 'The BD2K-LINCS Data Coordination and Integration Center is responsible for harmonizing LINCS data with other available resources',
    awardeeInstitution: 'Icahn School of Medicine at Mount Sinai',
    status: 'Data Coordination Center',
  },
  {
    name: 'BroadT LINCS',
    internalLink: `${dsgcBaseUrl}/lincs-transcriptomics`,
    url: 'https://clue.io/',
    iconUrl: 'http://lincsproject.org/LINCS/files/centers_logos/CMap.svg',
    description: 'The LINCS Center for Transcriptomics utilizes the L1000 technology to profile the response of human cells to thousands of perturbations',
    awardeeInstitution: 'Broad Institute',
    status: 'Data and Signature Generation Center',
  },
  {
    name: 'DToxS',
    internalLink: `${dsgcBaseUrl}/dtoxs`,
    url: 'https://martip03.u.hpc.mssm.edu/index.php',
    iconUrl: 'http://lincsproject.org/LINCS/files/centers_logos/DToxS.png',
    description: 'The Drug Toxicity Signature Generation Center develops cell signatures that predict adverse events that might be caused by drugs',
    awardeeInstitution: 'Icahn School of Medicine at Mount Sinai',
    status: 'Data and Signature Generation Center',
  },
  {
    name: 'HMS LINCS',
    internalLink: `${dsgcBaseUrl}/hms-lincs`,
    url: 'http://lincs.hms.harvard.edu/',
    iconUrl: 'http://lincsproject.org/LINCS/files/centers_logos/hms-lincs.png',
    description: 'The HMS LINCS Center collects and disseminates data and tools needed to understand how human cells respond to perturbations',
    awardeeInstitution: 'Harvard Medical School',
    status: 'Data and Signature Generation Center',
  },
  {
    name: 'LINCS PCCSE',
    internalLink: `${dsgcBaseUrl}/lincs-pccse`,
    url: 'https://panoramaweb.org/labkey/project/LINCS/begin.view',
    iconUrl: 'http://lincsproject.org/LINCS/files/centers_logos/lincs-pccse.png',
    description: 'The LINCS PCCSE utilizes the P100 and GCP assays to profile the response of human cell lines to perturbations',
    awardeeInstitution: 'Broad Institute',
    status: 'Data and Signature Generation Center',
  },
  {
    name: 'MEP LINCS',
    internalLink: `${dsgcBaseUrl}/mep-lincs`,
    url: 'https://www.synapse.org/#!Synapse:syn2862345',
    iconUrl: 'http://lincsproject.org/LINCS/files/centers_logos/mep-lincs-logo.png',
    description: 'The MEP LINCS Center utilizes microscopy to profile the effects of different MEs on the response of human cell lines to perturbations',
    awardeeInstitution: 'Oregon Health and Science University',
    status: 'Data and Signature Generation Center',
  },
  {
    name: 'NeuroLINCS',
    internalLink: `${dsgcBaseUrl}/neurolincs`,
    url: 'http://www.neurolincs.org/',
    iconUrl: 'http://lincsproject.org/LINCS/files/centers_logos/NeuroLINCS.png',
    description: 'The NeuroLINCS Center studies human brain cells derived from patient-derived iPS cells to understand the causes of neurological disease',
    awardeeInstitution: 'University of California-Irvine',
    status: 'Data and Signature Generation Center',
  },
  {
    newsTitle: 'NIH Awards Aim to Improve Understanding of Cell Pathways, Development of New Therapies',
    url: 'https://www.nih.gov/news-events/news-releases/nih-awards-aim-improve-understanding-cell-pathways-development-new-therapies',
    description: 'Building on a successful three-year pilot project, the National Institutes of Health has awarded more than $64 million to six research institutions to create a database of human cellular responses, the Library of Integrated Network-based Cellular Signatures (LINCS).',
  },
  {
    newsTitle: 'NIH Invests almost $32 Million to Increase Utility of Biomedical Research Data',
    url: 'https://www.nih.gov/news-events/news-releases/nih-invests-almost-32-million-increase-utility-biomedical-research-data',
    description: 'Wide-ranging National Institutes of Health grants will develop new strategies to analyze and leverage the explosion of increasingly complex biomedical data sets, often referred to as Big Data.',
  },
];
