import React, { Component, PropTypes } from 'react';
import { Link } from 'react-router';
import { push } from 'react-router-redux';
import { connect } from 'react-redux';

// import Cube from 'components/Cube';
import BarGraph from 'components/BarGraph';
import { loginUser } from 'actions/auth';
import styles from './HomeView.scss';

const mapStateToProps = (state) => ({
  entities: state.entities,
});

// TODO: Make a stateless function once completed. Leave for now to enable hot-reloading.
/* eslint react/prefer-stateless-function:0 */
export class HomeView extends Component {
  render() {
    return (
      <div className={styles.wrapper}>
        <div className={styles.banner}>
          <div className={`container ${styles.animated}`}>
            <img src={require('./cube.png')} alt="NIH LINCS Program" />
            <p className={styles.lead}>
              LINCS aims to create a network-based understanding of biology by cataloging changes
              in gene expression and other cellular processes that occur when cells are exposed
              to a variety of perturbing agents.
            </p>
            <Link
              to="/data/discover"
              className={`btn btn-outline-inverse btn-lg ${styles['btn-discover']}`}
            >
              Discover LINCS Data
            </Link>
            <Link
              to="/data/tools-databases"
              className={`btn btn-outline-inverse btn-lg ${styles['btn-td']}`}
            >
              Apps & Workflows
            </Link>
          </div>
        </div>
        <div className={styles.section}>
          <div className="container">
            <h2 id="getting-started" className={styles.title}>Getting Started</h2>
            <p className={styles['section-lead']}>
              Whether you'd like to use LINCS tools to analyze your own data or discover new data
              generated by the LINCS program, getting started is quick and easy.
            </p>
            <div className="row">
              <div className="col-sm-6 m-b-3">
                <BarGraph />
                <h4>Categorized and Curated Data</h4>
                <p>
                  Browse through the over 60 LINCS datasets, including both the metadata and
                  the raw data generated.
                </p>
                <Link
                  to="/discover#categories"
                  className={`btn btn-outline ${styles['btn-lincs']}`}
                >
                  View categories
                </Link>
              </div>
              <div className="col-sm-6 m-b-3">
                <div className={`${styles.tools} ${styles.animated}`}>
                  <img src={require('./responsive.png')} alt="responsive" />
                </div>
                <h4>Tools for All Platforms</h4>
                <p>
                  Analyze gene lists or query LINCS databases with a vast array of tools on all
                  platforms.
                </p>
                <Link
                  to="/tools#analysis"
                  className={`btn btn-outline ${styles['btn-lincs']}`}
                >
                  View Analysis Tools
                </Link>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.section}>
          <div className="container">
            <h2 className={styles.title}>Getting Started</h2>
            <p className={styles['section-lead']}>
              Whether you'd like to use LINCS tools to analyze your own data or discover new data
              generated by the LINCS program, getting started is quick and easy.
            </p>
            <div className="row">
              <div className="col-sm-6 m-b-3">
                <h4>Title about Discovering Data</h4>
                <p>
                  Discover data. Discover data. Discover data. Discover data. Discover data.
                  Discover data.
                </p>
              </div>
              <div className="col-sm-6 m-b-3">
                <h4>Title about LINCS tools</h4>
                <p>
                  LINCS tools. LINCS tools. LINCS tools. LINCS tools. LINCS tools.
                  LINCS tools.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

HomeView.propTypes = {
  loginUser: PropTypes.func,
  entities: PropTypes.object,
  push: PropTypes.func.isRequired,
};

export default connect(mapStateToProps, {
  loginUser,
  push,
})(HomeView);
