
INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'Dose-Response Cell Proliferation Analysis', 'Dose-Response Analysis of 6 Breast Cancer Cell Lines', 'Dose-dependent sensitivities of 6 nonmalignant breast and breast cancer cell lines', 'LDG-1241, LDG-1242, LDG-1243, LDG-1244, LDG-1245, LDG-1246,  LDG-1247', 'GR Browser', 'http://www.grcalculator.org/grbrowser/?dataset=Broad-HMS_LINCS_Joint_Project', 'The dose-dependent sensitivities of 6 nonmalignant breast and breast cancer cell lines were assayed by the HMS LINCS Center by measuring cell counts 72 hours after treatment with each of 107 small molecule perturbagens across a 6-point dose range.', '"drug response", "dose response", "breast cancer", "gr metrics", "gr50", "grmax"');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'Dose-Response Cell Proliferation Analysis', 'Dose-Response Analysis of MCF 10A', 'Dose-dependent sensitivities of three independent batches and one derivative of MCF 10A cell line', 'HMS-20278, HMS-20279, HMS-20280, HMS-20281, HMS-20282, HMS-20283, HMS-20284, HMS-20285, HMS-20286', 'GR Browser', 'http://www.grcalculator.org/grbrowser/?dataset=LINCS_MCF_10A_Common_Project', 'The dose-dependent sensitivities of three independent batches and one derivative of the nonmalignant breast cell line MCF 10A were assayed independently by five of the LINCS DSGCs by measuring cell counts using imaging or by estimating cell proliferation using the CellTiter-Glo_ assay 72 hours after treatment with each of 8 small molecule perturbagens across a 9-point dose range.', '"drug response", "dose response", "breast cancer", "gr metrics", "gr50", "grmax"');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'Dose-Response Cell Proliferation Analysis', 'Dose-Response Analysis of Seeding Density', 'Density- and context-dependent sensitivities of 6 breast cancer cell lines plated at 6 different cell densities', 'LDG-1252, LDG-1253, LDG-1254', 'GR Browser', 'http://www.grcalculator.org/grbrowser/?dataset=HMS_LINCS_Seeding_Density_Project', 'The density- and context-dependent sensitivities of 6 breast cancer cell lines plated at 6 different cell densities were assayed by the HMS LINCS Center by measuring cell counts using imaging 72 hours after treatment with each of 12 small molecule inhibitors across a 9-point dose range.', '"drug response", "dose response", "breast cancer", "gr metrics", "gr50", "grmax"');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'Dose-Response Cell Proliferation Analysis', 'Dose-Response Analysis of 73 Breast Cancer Cell Lines', 'Dose-dependent sensitivities of 73 nonmalignant breast and breast cancer cell lines ', 'HMS-20268, HMS-20269, HMS-20270, HMS-20271', 'GR Browser', 'http://www.grcalculator.org/grbrowser/?dataset=MEP-HMS_LINCS_Joint_Project', 'The dose-dependent sensitivities of 73 nonmalignant breast and breast cancer cell lines were assayed by the MEP LINCS Center by estimating proliferation using the CellTiter-Glo_ assay 72 hours after treatment with each of 139 small molecule and antibody perturbagens across a 9-point dose range. Analysis of a subset of these data using traditional growth inhibition metrics (GI50) was previously described in Heiser et al. (2012) (PMID: 22003129) and Daemen et al. (2013) (PMID: 24176112). Here, the complete dataset was reanalyzed by the HMS LINCS Center using GR metrics to account for differences in growth rates across the cell lines and treatment conditions.', '"drug response", "dose response", "breast cancer", "gr metrics", "gr50", "grmax"');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS2 Analysis of PC3 Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for PC3 cells (Staining Set 2)', 'LDS-1240', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706745', 'Analysis of cell cycle and nuclear state imaging data from PC3 (prostate cancer) cell lines treated with ligands and ECM proteins (Staining Set 2), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS1 Analysis of MCF7 Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for MCF7 cells (Staining Set 1)', 'LDS-1299', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706725', 'Analysis of cell cycle and nuclear state imaging data from MCF7 (breast cancer) cell lines treated with ligands and ECM proteins (Staining Set 1), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS2 Analysis of MCF7 Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for MCF7 cells (Staining Set 2)', 'LDS-1303', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706727', 'Analysis of cell cycle and nuclear state imaging data from MCF7 (breast cancer) cell lines treated with ligands and ECM proteins (Staining Set 2), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS3 Analysis of MCF7 Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for MCF7 cells (Staining Set 3)', 'LDS-1307', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706729', 'Analysis of cell cycle and nuclear state imaging data from MCF7 (breast cancer) cell lines treated with ligands and ECM proteins (Staining Set 3), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS1 Analysis of PC3 Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for PC3 cells (Staining Set 1)', 'LDS-1311', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706712', 'Analysis of cell cycle and nuclear state imaging data from PC3 (prostate cancer) cell lines treated with ligands and ECM proteins (Staining Set 1), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS2 Analysis of PC3 Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for PC3 cells (Staining Set 2)', 'LDS-1319', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706747', 'Analysis of cell cycle and nuclear state imaging data from PC3 (prostate cancer) cell lines treated with ligands and ECM proteins (Staining Set 2, no H3), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS3 Analysis of PC3 Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for PC3 cells (Staining Set 3)', 'LDS-1323', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706749', 'Analysis of cell cycle and nuclear state imaging data from PC3 (prostate cancer) cell lines treated with ligands and ECM proteins (Staining Set 3), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS1 Analysis of YAPC Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for YAPC cells (Staining Set 1)', 'LDS-1327', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706751', 'Analysis of cell cycle and nuclear state imaging data from YAPC (pancreas carcinoma) cell lines treated with ligands and ECM proteins (Staining Set 1), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS2 Analysis of YAPC Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for YAPC cells (Staining Set 2)', 'LDS-1331', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5711121', 'Analysis of cell cycle and nuclear state imaging data from YAPC (pancreas carcinoma) cell lines treated with ligands and ECM proteins (Staining Set 2), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Imaging Analysis', 'MEMA Analysis', 'SS3 Analysis of YAPC Cells with MEMA ', 'Cell cycle and nuclear state imaging readouts for YAPC cells (Staining Set 3)', 'LDS-1335', 'LINCS Data Explorer', 'https://www.synapse.org/#!Synapse:syn5706755', 'Analysis of cell cycle and nuclear state imaging data from YAPC (pancreas carcinoma) cell lines treated with ligands and ECM proteins (Staining Set 3), profiled to explore the role of microenvironment in cancer growth.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Proteomics Analysis', '', 'P100 Analysis of 45 Perturbations', '141 samples from 3 cell lines under ~45 perturbational conditions profiled by MS-based proteomics', 'LDS-1196', 'iLINCS', 'http://www.ilincs.org/GenomicsPortals/DatasetLandingPage.do?data_set=LDG-1193', 'Interactive visualization of mass spectrometry-based proteomics assay data to detect 90 phosphopeptide probes in 141 samples from 3 cell lines across ~45 perturbations.  LINCS PCCSE - P100 validation set.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Transcriptomics Analysis', '', 'Analysis of RNA-seq from SMA and ALS iPSCs', '35 RNA-seq samples from iPSCs derived from ALS, SMA, and Control individuals', 'LDS-1356', 'iLINCS', 'http://www.ilincs.org/GenomicsPortals/DatasetLandingPage.do?data_set=LDG-1232', 'Interactive visualization of RNA-seq data from 35 human brain cell type samples, profiled to develop a network of cell signatures relevant to Amyotrophic Lateral Sclerosis (ALS) and Spinal Muscular Atrophy (SMA).  NeuroLINCS - RNA-seq gene expression (August 2015).', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Transcriptomics Analysis', '', 'Analysis of RNA-seq cardiomyocytes treated with drugs', '183 RNA-seq samples from cardiomyocytes treated with FDA-approved drugs', 'LDS-1237', 'iLINCS', 'http://www.ilincs.org/GenomicsPortals/DatasetLandingPage.do?data_set=LDG-1231', 'Interactive visualization of RNA-seq data from 183 samples of human cell lines, profiled to develop cellular signatures for drug-induced toxicity caused by FDA approved drugs and toxicity mitigation by coadministration of other drugs.  DToxS - RNA-seq gene expression (May 2015).', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Proteomics Analysis', '', 'P100 Analysis of 32 Epigenetic Compounds', '456 samples from 5 cell lines perturbed by 32 epigenetic compounds profiled by MS-based proteomics', 'LDG-1285', 'iLINCS', 'http://www.ilincs.org/GenomicsPortals/DatasetLandingPage.do?data_set=LDG-1228', 'Interactive visualization of mass spectrometry-based proteomics assay data to detect 96 phosphopeptide probes in 465 samples of 5 cell lines perturbed by 32 epigenetic compounds.  LINCS PCCSE - P100 data - epigenetic compounds.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Transcriptomics Analysis', '', 'Analysis of RNA-seq cardiomyocytes treated with drugs', '378 RNA-seq samples from cardiomyocytes treated with drugs', 'LDS-1239', 'iLINCS', 'http://www.ilincs.org/GenomicsPortals/DatasetLandingPage.do?data_set=LDG-1233', 'Interactive visualization of RNA-seq data from 378 samples of human cell lines, profiled to develop cellular signatures for drug-induced toxicity caused by FDA approved drugs and toxicity mitigation by coadministration of other drugs.  DToxS - RNA-seq gene expression (August 2015).', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Proteomics Analysis', '', 'P100 Analysis of 32 Kinase Inhibitors', '373 samples from 2 cell lines perturbed by 32 kinase inhibitors profiled by MS-based proteomics', 'LDG-1285', 'iLINCS', 'http://www.ilincs.org/GenomicsPortals/DatasetLandingPage.do?data_set=LDG-1255', 'Interactive visualization of mass spectrometry-based proteomics assay data to detect 94 phosphopeptide probes in 373 samples of 2 cell lines perturbed by 32 kinase inhibitors.  LINCS PCCSE - kinase inhibitors.', '');

INSERT INTO `canned_analyses` (grouping, subgrouping, title, subtitle, dataset_accessions_list, tool_name, canned_analysis_url, canned_analysis_description, metadata)
VALUES ('Proteomics Analysis', '', 'GCP Analysis of 32 Kinase Inhibitors', '287 samples from 3 cell lines perturbed by 32 kinase inhibitors profiled by MS-based proteomics', 'LDG-1284', 'iLINCS', 'http://www.ilincs.org/GenomicsPortals/DatasetLandingPage.do?data_set=LDG-1256', 'Interactive visualization of mass spectrometry-based proteomics assay data to detect 53 histone proteins in 287 samples of 3 cell lines perturbed by 32 kinase inhibitors.  LINCS PCCSE - GCP data - kinase inhibitors.', '');
