/* eslint max-len: 0 */

module.exports = [
  {
    title: 'BD2K-LINCS-DCIC External Data Science Research Projects',
    description: 'The BD2K-LINCS Data Coordination and Integration Center (DCIC) is soliciting applications from the scientific community for data science research collaborations with the DCIC that focus on mining and integrating data generated by the LINCS program for new scientific discovery.',
    date: new Date('2015-09-01T06:00:00.000Z'),
    release_date: new Date('2015-01-19T06:00:00.000Z'),
    open_date: new Date('2015-05-01T06:00:00.000Z'),
    due_date: new Date('2015-09-01T06:00:00.000Z'),
    review_date: new Date('2015-11-01T06:00:00.000Z'),
    announced_date: new Date('2016-01-01T06:00:00.000Z'),
    start_date: new Date('2016-05-01T06:00:00.000Z'),
    key_links: JSON.stringify({
      'Request for Applications': 'http://lincs-dcic.org/#/edsr#nav',
      'BD2K-LINCS Data Coordination and Integration Center (DCIC)': 'http://lincs-dcic.org/#/',
    }),
  },
  {
    title: 'Supplements to Extend the Scope and Reach of LINCS Datasets',
    description: 'This notice (NOT-RM-15-102) announces an opportunity to request administrative supplements to existing NIH research grants, to support generation of new data that will also advance the goals of the LINCS program.',
    date: new Date('2015-05-15T06:00:00.000Z'),
    release_date: new Date('2015-02-20T06:00:00.000Z'),
    open_date: null,
    due_date: new Date('2015-05-15T06:00:00.000Z'),
    review_date: null,
    announced_date: null,
    start_date: new Date('2015-07-01T06:00:00.000Z'),
    key_links: JSON.stringify({
      'NOT_RM-15-102': 'http://grants.nih.gov/grants/guide/notice-files/NOT-RM-15-012.html',
    }),
  },
];
