module.exports = [{
  "pmc_id": "PMC4456804",
  "year_published": 2015,
  "pm_id": "260484152",
  "article_name": "Dynamics of the discovery process of protein-protein interactions from low content studies.",
  "authors": ["Wang Z", "Clark NC", "Ma'ayan A"],
  "issue": "1",
  "pp_pages": "26",
  "journal_name": "BMC Systems Biology",
  "comp_tools": [{
    "name": "Custom code"
  }],
  "doi": "10.1186/s12918-015-0173-z",
  "other_link": null,
  "volume": "9",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": null,
  "year_published": 2015,
  "pm_id": "25971742",
  "article_name": "GEO2Enrichr: browser extension and server app to extract gene sets from GEO and analyze them for biological functions.",
  "authors": ["Gundersen GW", "Jones MR", "Rouillard AD", "Kou Y", "Monteiro CD", "Feldmann AS", "Hu KS", "Ma'ayan A"],
  "issue": null,
  "pp_pages": null,
  "journal_name": "Bioinformatics",
  "comp_tools": [{
    "url": "http://amp.pharm.mssm.edu/g2e/",
    "name": "GEO2Enrichr",
    "description": "A web application and two browser extensions (one for Chrome and another for Firefox) designed to ease the extraction of signatures from studies posted on the Gene Expression Omnibus (GEO) database. These signatures are then submitted to Enrichr, a gene signature search engine containing over 70,000 annotated signatures, for downstream functional analysis."
  }, {
    "name": "Enrichr",
    "url": "http://amp.pharm.mssm.edu/Enrichr"
  }],
  "doi": "pii:btv297",
  "other_link": null,
  "volume": null,
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4380931",
  "year_published": 2015,
  "pm_id": "25814555",
  "article_name": "Systematic analysis of BRAFV600E melanomas reveals a role for JNK/c-Jun pathway in adaptive resistance to drug-induced apoptosis.",
  "authors": ["Fallahi-Sichani M", "Moerke NJ", "Niepel M", "Zhang T", "Gray NS", "Sorger PK"],
  "issue": "3",
  "pp_pages": "797",
  "journal_name": "Molecular Systems Biology ",
  "comp_tools": [{
    "name": "Data exploration website",
    "url": "http://lincs.hms.harvard.edu/fallahi-sichani-molsystbiol-2015/"
  }],
  "doi": "10.15252/msb.20145877",
  "other_link": null,
  "volume": "11",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": true,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4383998",
  "year_published": 2015,
  "pm_id": "25514926",
  "article_name": "PhosphoSitePlus, 2014: mutations, PTMs and recalibrations.",
  "authors": ["Hornbeck PV", "Zhang B", "Murray B", "Kornhauser JM", "Latham V", "Skrzypek E"],
  "issue": "Database issue",
  "pp_pages": "D512-20",
  "journal_name": "Nucleic Acids Research",
  "comp_tools": [{
    "name": "PhosphoSitePlus",
    "url": "http://www.phosphosite.org/"
  }],
  "doi": "10.1093/nar/gku1267",
  "other_link": null,
  "volume": "43",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4270428",
  "year_published": 2014,
  "pm_id": "25522349",
  "article_name": "Multitask learning of signaling and regulatory networks with application to studying human response to flu.",
  "authors": ["Jain S", "Gitter A", "Bar-Joseph Z"],
  "issue": "12",
  "pp_pages": "e1003943",
  "journal_name": "PLoS Computational Biology",
  "comp_tools": [{
    "name": "Custom code"
  }],
  "doi": "10.1371/journal.pcbi.1003943",
  "other_link": null,
  "volume": "10",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4221125",
  "year_published": 2014,
  "pm_id": "25100688",
  "article_name": "Drug/Cell-line Browser: interactive canvas visualization of cancer drug/cell-line viability assay datasets",
  "authors": ["Duan Q", "Wang Z", "Fernandez NF", "Rouillard AD", "Tan CM", "Benes CH", "Ma'ayan A"],
  "issue": "22",
  "pp_pages": "3289-90",
  "journal_name": "Bioinformatics",
  "comp_tools": [{
    "name": "LINCS Drug/Cell-line Browser",
    "url": "http://www.maayanlab.net/LINCS/DCB/"
  }],
  "doi": "10.1093/bioinformatics/btu526",
  "other_link": null,
  "volume": "30",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4243058",
  "year_published": 2014,
  "pm_id": "25417160",
  "article_name": "A noncanonical Frizzled2 pathway regulates epithelial-mesenchymal transition and metastasis.",
  "authors": ["Gujral TS", "Chan M", "Peshkin L", "Sorger PK", "Kirschner MW", "MacBeath G"],
  "issue": "4",
  "pp_pages": "844-56",
  "journal_name": "Cell",
  "comp_tools": [],
  "doi": "10.1016/j.cell.2014.10.032",
  "other_link": null,
  "volume": "159",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4201337",
  "year_published": 2014,
  "pm_id": "25089360",
  "article_name": "An unbiased approach to identify endogenous substrates of \"histone\" deacetylase 8.",
  "authors": ["Olson DE", "Udeshi ND", "Wolfson NA", "Pitcairn CA", "Sullivan ED", "Jaffe JD", "Svinkina T", "Natoli T", "Lu X", "Paulk J", "McCarren P", "Wagner FF", "Barker D", "Howe E", "Lazzaro F", "Gale JP", "Zhang YL", "Subramanian A", "Fierke CA", "Carr SA", "Holson EB"],
  "issue": "10",
  "pp_pages": "2210-6",
  "journal_name": "ACS Chemical Biology",
  "comp_tools": [{
    "name": "Lincscloud P100 API",
    "url": "http://api.lincscloud.org/p100"
  }],
  "doi": "10.1021/cb500492r",
  "other_link": null,
  "volume": "9",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4274604",
  "year_published": 2014,
  "pm_id": "25299921",
  "article_name": "A blueprint of cell identity.",
  "authors": ["Ma'ayan A", "Duan Q"],
  "issue": "10",
  "pp_pages": "1007-8",
  "journal_name": "Nature Biotechnology",
  "comp_tools": [{
    "name": "CellNet",
    "url": "http://cellnet.hms.harvard.edu/"
  }],
  "doi": "10.1038/nbt.3035",
  "other_link": null,
  "volume": "32",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": true,
}, {
  "pmc_id": "PMC4179751",
  "year_published": 2014,
  "pm_id": "25324859",
  "article_name": "Large-scale integration of small molecule-induced genome-wide transcriptional responses, Kinome-wide binding affinities and cell-growth inhibition profiles reveal global trends characterizing systems-level drug action.",
  "authors": ["Vidovi\u0107 D", "Koleti A", "Sch\u00fcrer SC"],
  "issue": null,
  "pp_pages": "342",
  "journal_name": "Frontiers in Genetics",
  "comp_tools": [{
    "name": "LIFE",
    "url": "http://life.ccs.miami.edu/life/"
  }],
  "doi": "10.3389/fgene.2014.00342",
  "other_link": null,
  "volume": "5",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4156235",
  "year_published": 2014,
  "pm_id": "25102069",
  "article_name": "Panorama: a targeted proteomics knowledge base.",
  "authors": ["Sharma V", "Eckels J", "Taylor GK", "Shulman NJ", "Stergachis AB", "Joyner SA", "Yan P", "Whiteaker JR", "Halusa GN", "Schilling B", "Gibson BW", "Colangelo CM", "Paulovich AG", "Carr SA", "Jaffe JD", "MacCoss MJ", "MacLean B"],
  "issue": "9",
  "pp_pages": "4205-10",
  "journal_name": "Journal of Proteome Research",
  "comp_tools": [{
    "name": "Lincscloud P100 API",
    "url": "http://api.lincscloud.org/p100"
  }],
  "doi": "10.1021/pr5006636",
  "other_link": null,
  "volume": "13",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4153537",
  "year_published": 2014,
  "pm_id": "25109570",
  "article_name": "Lean Big Data integration in systems biology and systems pharmacology.",
  "authors": ["Ma'ayan A", "Rouillard AD", "Clark NR", "Wang Z", "Duan Q", "Kou Y"],
  "issue": "9",
  "pp_pages": "450-60",
  "journal_name": "Trends in Pharmacological Sciences",
  "comp_tools": [{
    "name": "Review of multiple tools and databases"
  }],
  "doi": "10.1016/j.tips.2014.07.001",
  "other_link": null,
  "volume": "35",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": true,
}, {
  "pmc_id": "PMC4137659",
  "year_published": 2014,
  "pm_id": "25165633",
  "article_name": "Fast and accurate semantic annotation of bioassays exploiting a hybrid of machine learning and user confirmation.",
  "authors": ["Clark AM", "Bunin BA", "Litterman NK", "Schürer SC", "Visser U"],
  "issue": null,
  "pp_pages": "e524",
  "journal_name": "PeerJ",
  "comp_tools": [{
    "name": "LIFE",
    "url": "http://life.ccs.miami.edu/life/"
  }],
  "doi": "10.7717/peerj.524",
  "other_link": null,
  "volume": "2",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": true,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4086130",
  "year_published": 2014,
  "pm_id": "24906883",
  "article_name": "LINCS Canvas Browser: interactive web app to query, browse and interrogate LINCS L1000 gene expression signatures.",
  "authors": ["Duan Q", "Flynn C", "Niepel M", "Hafner M", "Muhlich JL", "Fernandez NF", "Rouillard AD", "Tan CM", "Chen EY", "Golub TR", "Sorger PK", "Subramanian A", "Ma'ayan A"],
  "issue": null,
  "pp_pages": "W449-60",
  "journal_name": "Nucleic Acids Research",
  "comp_tools": [{
    "name": "LINCS Canvas Browser",
    "url": "http://www.maayanlab.net/LINCS/LCB"
  }],
  "doi": "10.1093/nar/gku476",
  "other_link": null,
  "volume": "42",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4108877",
  "year_published": 2014,
  "pm_id": "25093074",
  "article_name": "Evolving BioAssay Ontology (BAO): modularization, integration and applications.",
  "authors": ["Abeyruwan S", "Vempati UD", "K\u00fc\u00e7\u00fck-McGinty H", "Visser U", "Koleti A", "Mir A", "Sakurai K", "Chung C", "Bittker JA", "Clemons PA", "Brudz S", "Siripala A", "Morales AJ", "Romacker M", "Twomey D", "Bureeva S", "Lemmon V", "Sch\u00fcrer SC"],
  "issue": "Suppl 1 Proceedings of the Bio-Ontologies Spec Interest G",
  "pp_pages": "S5",
  "journal_name": "Journal of Biomedical Semantics",
  "comp_tools": [{
    "name": "LIFE",
    "url": "http://life.ccs.miami.edu/life/"
  }],
  "doi": "10.1186/2041-1480-5-S1-S5",
  "other_link": null,
  "volume": "5",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": true,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3990667",
  "year_published": 2014,
  "pm_id": "24058034",
  "article_name": "Red blood cells tracking using optical flow methods.",
  "authors": ["Guo D", "van de Ven AL", "Zhou X"],
  "issue": "3",
  "pp_pages": "991-8",
  "journal_name": "IEEE Journal of Biomedical and Health Informatics",
  "comp_tools": [{
    "name": "CellIA"
  }],
  "doi": "10.1109/JBHI.2013.2281915",
  "other_link": null,
  "volume": "18",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4234128",
  "year_published": 2014,
  "pm_id": "24655548",
  "article_name": "Analysis of growth factor signaling in genetically diverse breast cancer lines.",
  "authors": ["Niepel M", "Hafner M", "Pace EA", "Chung M", "Chai DH", "Zhou L", "Muhlich JL", "Schoeberl B", "Sorger PK"],
  "issue": null,
  "pp_pages": "20",
  "journal_name": "BMC Biology",
  "comp_tools": [{
    "name": "Data exploration website",
    "url": "http://lincs.hms.harvard.edu/fallahi-sichani-molsystbiol-2015/"
  }],
  "doi": "10.1186/1741-7007-12-20",
  "other_link": null,
  "volume": "12",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": true,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": null,
  "year_published": 2014,
  "pm_id": "24518066",
  "article_name": "Metadata Standard and Data Exchange Specifications to Describe, Model, and Integrate Complex and Diverse High-Throughput Screening Data from the Library of Integrated Network-based Cellular Signatures (LINCS).",
  "authors": ["Vempati UD", "Chung C", "Mader C", "Koleti A", "Datar N", "Vidovi\u0107 D", "Wrobel D", "Erickson S", "Muhlich JL", "Berriz G", "Benes CH", "Subramanian A", "Pillai A", "Shamu CE", "Sch\u00fcrer SC"],
  "issue": "5",
  "pp_pages": "803-816",
  "journal_name": "Journal of Biomolecular Screening",
  "comp_tools": [{
    "name": "LIFE",
    "url": "http://life.ccs.miami.edu/life/"
  }],
  "doi": null,
  "other_link": null,
  "volume": "19",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": true,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3771683",
  "year_published": 2013,
  "pm_id": "23607489",
  "article_name": "Mass spectrometry based method to increase throughput for kinome analyses using ATP probes.",
  "authors": ["McAllister FE", "Niepel M", "Haas W", "Huttlin E", "Sorger PK", "Gygi SP"],
  "issue": "9",
  "pp_pages": "4666-74",
  "journal_name": "Analytical Chemistry",
  "comp_tools": [],
  "doi": "10.1021/ac303478g",
  "other_link": null,
  "volume": "85",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3637064",
  "year_published": 2013,
  "pm_id": "23586463",
  "article_name": "Enrichr: Interactive and collaborative HTML5 gene list enrichment analysis tool",
  "authors": ["Chen EY", "Tan CM", "Kou Y", "Duan Q", "Wang Z", "Vaz Meirelles G", "Clark NR", "Ma'ayan A"],
  "issue": null,
  "pp_pages": "128",
  "journal_name": "BMC Bioinformatics",
  "comp_tools": [{
    "name": "Enrichr",
    "url": "http://amp.pharm.mssm.edu/Enrichr"
  }],
  "doi": "10.1186/1471-2105-14-128",
  "other_link": null,
  "volume": "14",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3692096",
  "year_published": 2013,
  "pm_id": "23748957",
  "article_name": "The UCSC Interaction Browser: multidimensional data views in pathway context.",
  "authors": ["Wong CK", "Vaske CJ", "Ng S", "Sanborn JZ", "Benz SC", "Haussler D", "Stuart JM"],
  "issue": "Web Server issue",
  "pp_pages": "W218-24",
  "journal_name": "Nucleic Acids Research",
  "comp_tools": [{
    "name": "UCSC Interaction Browser"
  }],
  "doi": "10.1093/nar/gkt473",
  "other_link": null,
  "volume": "41",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3764016",
  "year_published": 2013,
  "pm_id": "24039560",
  "article_name": "Genome-wide signatures of transcription factor activity: connecting transcription factors, disease, and small molecules.",
  "authors": ["Chen J", "Hu Z", "Phatak M", "Reichard J", "Freudenberg JM", "Sivaganesan S", "Medvedovic M"],
  "issue": "9",
  "pp_pages": "e1003198",
  "journal_name": "PLoS Computational Biology",
  "comp_tools": [{
    "name": "TREG",
    "url": "http://genomicsportals.org/"
  }],
  "doi": "10.1371/journal.pcbi.1003198",
  "other_link": null,
  "volume": "9",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3609407",
  "year_published": 2013,
  "pm_id": "23321554",
  "article_name": "Functionalizing genomic data for personalization of medicine.",
  "authors": ["Benes CH"],
  "issue": "4",
  "pp_pages": "309-11",
  "journal_name": "Clinical Pharmacology and Therapeutics",
  "comp_tools": [],
  "doi": "10.1038/clpt.2012.219",
  "other_link": null,
  "volume": "93",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": true,
}, {
  "pmc_id": "PMC3615534",
  "year_published": 2013,
  "pm_id": "23836026",
  "article_name": "Metasignatures identify two major subtypes of breast cancer.",
  "authors": ["Duan Q", "Kou Y", "Clark NR", "Gordonov S", "Ma'ayan A"],
  "issue": null,
  "pp_pages": "e35",
  "journal_name": "CPT: Pharmacometrics and Systems Pharmacology",
  "comp_tools": [],
  "doi": "10.1038/psp.2013.11",
  "other_link": null,
  "volume": "2",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3760004",
  "year_published": 2013,
  "pm_id": "23436801",
  "article_name": "Characterization of Torin2, an ATP-competitive inhibitor of mTOR, ATM, and ATR.",
  "authors": ["Liu Q", "Xu C", "Kirubakaran S", "Zhang X", "Hur W", "Liu Y", "Kwiatkowski NP", "Wang J", "Westover KD", "Gao P", "Ercan D", "Niepel M", "Thoreen CC", "Kang SA", "Patricelli MP", "Wang Y", "Tupper T", "Altabef A", "Kawamura H", "Held KD", "Chou DM", "Elledge SJ", "Janne PA", "Wong KK", "Sabatini DM", "Gray NS"],
  "issue": "8",
  "pp_pages": "2574-86",
  "journal_name": "Cancer Research",
  "comp_tools": [],
  "doi": "10.1158/0008-5472.CAN-12-1702",
  "other_link": null,
  "volume": "73",
  "assay_development": true,
  "data_analysis": false,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3947796",
  "year_published": 2013,
  "pm_id": "24013279",
  "article_name": "Metrics other than potency reveal systematic variation in responses to cancer drugs.",
  "authors": ["Fallahi-Sichani M", "Honarnejad S", "Heiser LM", "Gray JW", "Sorger PK "],
  "issue": "11",
  "pp_pages": "708-14",
  "journal_name": "Nature Chemical Biology",
  "comp_tools": [{
    "name": "Data exploration website",
    "url": "http://lincs.hms.harvard.edu/fallahi-sichani-molsystbiol-2015/"
  }],
  "doi": null,
  "other_link": null,
  "volume": "9",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4098832",
  "year_published": 2013,
  "pm_id": "24185007",
  "article_name": "A melanocyte lineage program confers resistance to MAP kinase pathway inhibition.",
  "authors": ["Johannessen CM", "Johnson LA", "Piccioni F", "Townes A", "Frederick DT", "Donahue MK", "Narayan R", "Flaherty KT", "Wargo JA", "Root DE", "Garraway LA"],
  "issue": "7478",
  "pp_pages": "138-42",
  "journal_name": "Nature",
  "comp_tools": [{
    "name": "KS Query and GSEA"
  }],
  "doi": "10.1038/nature12688",
  "other_link": null,
  "volume": "504",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3589817",
  "year_published": 2013,
  "pm_id": "23339603",
  "article_name": "High-throughput secretomic analysis of single cells to assess functional cellular heterogeneity.",
  "authors": ["Lu Y", "Chen JJ", "Mu L", "Xue Q", "Wu Y", "Wu PH", "Li J", "Vortmeyer AO", "Miller-Jensen K", "Wirtz D", "Fan R"],
  "issue": "4",
  "pp_pages": "2548-56",
  "journal_name": "Analytical Chemistry",
  "comp_tools": [{
    "name": "MATLAB scripts"
  }],
  "doi": "10.1021/ac400082e",
  "other_link": null,
  "volume": "85",
  "assay_development": true,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3845839",
  "year_published": 2013,
  "pm_id": "24065145",
  "article_name": "Profiles of basal and stimulated receptor signaling networks predict drug response in breast cancer lines.",
  "authors": ["Niepel M", "Hafner M", "Pace EA", "Chung M", "Chai DH", "Zhou L", "Schoeberl B", "Sorger PK"],
  "issue": "294",
  "pp_pages": "ra84",
  "journal_name": "Science Signaling",
  "comp_tools": [{
    "name": "Data exploration website",
    "url": "http://lincs.hms.harvard.edu/fallahi-sichani-molsystbiol-2015/"
  }],
  "doi": "10.1126/scisignal.2004379",
  "other_link": null,
  "volume": "6",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": true,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3799471",
  "year_published": 2013,
  "pm_id": "23986566",
  "article_name": "Discovering causal pathways linking genomic events to transcriptional states using tied diffusion through interacting events (TieDIE).",
  "authors": ["Paull EO", "Carlin DE", "Niepel M", "Sorger PK", "Haussler D", "Stuart JM"],
  "issue": "21",
  "pp_pages": "2757-64",
  "journal_name": "Bioinformatics",
  "comp_tools": [{
    "name": "TieDIE",
    "url": "https://sysbiowiki.soe.ucsc.edu/tiedie"
  }],
  "doi": "10.1093/bioinformatics/btt471",
  "other_link": null,
  "volume": "29",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": true,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3959726",
  "year_published": 2013,
  "pm_id": "23869022",
  "article_name": "Tight coordination of protein translation and HSF1 activation supports the anabolic malignant state.",
  "authors": ["Santagata S", "Mendillo ML", "Tang YC", "Subramanian A", "Perley CC", "Roche SP", "Wong B", "Narayan R", "Kwon H", "Koeva M", "Amon A", "Golub TR", "Porco JA Jr", "Whitesell L", "Lindquist S"],
  "issue": "6134",
  "pp_pages": "1238303",
  "journal_name": "Science",
  "comp_tools": [{
    "name": "KS Query"
  }],
  "doi": "10.1126/science",
  "other_link": null,
  "volume": "341",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3569091",
  "year_published": 2013,
  "pm_id": "23259810",
  "article_name": "Kinome-wide activity modeling from diverse public high-quality data sets.",
  "authors": ["Sch\u00fcrer SC", "Muskal SM"],
  "issue": "1",
  "pp_pages": "27-38",
  "journal_name": "Journal of Chemical Information Modeling",
  "comp_tools": [{
    "name": "LIFE",
    "url": "http://life.ccs.miami.edu/life/"
  }],
  "doi": "10.1021/ci300403k",
  "other_link": null,
  "volume": "53",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3855094",
  "year_published": 2013,
  "pm_id": "24339888",
  "article_name": "Systematically studying kinase inhibitor induced signaling network signature by integrating both therapeutic and side effects. ",
  "authors": ["Shao H", "Peng T", "Ji Z", "Su J", "Zhou X"],
  "issue": "12",
  "pp_pages": "e80832",
  "journal_name": "PLoS One",
  "comp_tools": [{
    "name": "KIEP",
    "url": "http://ctsb.is.wfubmc.edu/itNETZ/KIEP.html"
  }],
  "doi": "10.1371/journal.pone.0080832",
  "other_link": null,
  "volume": "8",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3712222",
  "year_published": 2013,
  "pm_id": "23749960",
  "article_name": "Network2Canvas: Network visualization on a canvas with enrichment analysis.",
  "authors": ["Tan CM", "Chen EY", "Dannenfelser R", "Clark NR", "Ma'ayan A"],
  "issue": "15",
  "pp_pages": "1872-8",
  "journal_name": "Bioinformatics",
  "comp_tools": [{
    "name": "Network2Canvas",
    "url": "http://www.maayanlab.net/N2C"
  }],
  "doi": null,
  "other_link": null,
  "volume": "29",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3783590",
  "year_published": 2013,
  "pm_id": "23788527",
  "article_name": "Differential determinants of cancer cell insensitivity to antimitotic drugs discriminated by a one-step cell imaging assay.",
  "authors": ["Tang Y", "Xie T", "Florian S", "Moerke N", "Shamu C", "Benes C", "Mitchison TJ "],
  "issue": "9",
  "pp_pages": "1062-71",
  "journal_name": "Journal of Biomolecular Screening",
  "comp_tools": [],
  "doi": "10.1177/1087057113493804",
  "other_link": null,
  "volume": "18",
  "assay_development": true,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3782379",
  "year_published": 2013,
  "pm_id": "24078772",
  "article_name": "A fluorescent colorimetric pH sensor and the influences of matrices on sensing performances.",
  "authors": ["Tian Y", "Fuller E", "Klug S", "Lee F", "Su F", "Zhang L", "Chao S", "Meldrum D"],
  "issue": null,
  "pp_pages": "1-10",
  "journal_name": "Sensors and Actuators B, Chemical",
  "comp_tools": [],
  "doi": null,
  "other_link": null,
  "volume": "188",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3878311",
  "year_published": 2013,
  "pm_id": "24090834",
  "article_name": "A dual sensor for real-time monitoring of glucose and oxygen. ",
  "authors": ["Zhang L", "Su F", "Buizer S", "Lu H", "Gao W", "Tian Y", "Meldrum D"],
  "issue": "38",
  "pp_pages": "9779-88",
  "journal_name": "Biomaterials",
  "comp_tools": [],
  "doi": "10.1016/j.biomaterials.2013.09.031",
  "other_link": null,
  "volume": "34",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3349233",
  "year_published": 2012,
  "pm_id": "22460902",
  "article_name": "Systematic identification of genomic markers of drug sensitivity in cancer cells.",
  "authors": ["Garnett MJ", "Edelman EJ", "Heidorn SJ", "Greenman CD", "Dastur A", "Lau KW", "Greninger P", "Thompson IR", "Luo X", "Soares J", "Liu Q", "Iorio F", "Surdez D", "Chen L", "Milano RJ", "Bignell GR", "Tam AT", "Davies H", "Stevenson JA", "Barthorpe S", "Lutz SR", "Kogera F", "Lawrence K", "McLaren-Douglas A", "Mitropoulos X", "Mironenko T", "Thi H", "Richardson L", "Zhou W", "Jewitt F", "Zhang T", "O'Brien P", "Boisvert JL", "Price S", "Hur W", "Yang W", "Deng X", "Butler A", "Choi HG", "Chang JW", "Baselga J", "Stamenkovic I", "Engelman JA", "Sharma SV", "Delattre O", "Saez-Rodriguez J", "Gray NS", "Settleman J", "Futreal PA", "Haber DA", "Stratton MR", "Ramaswamy S", "McDermott U", "Benes CH"],
  "issue": "7391",
  "pp_pages": "570-5",
  "journal_name": "Nature",
  "comp_tools": [],
  "doi": "10.1038/nature11005",
  "other_link": null,
  "volume": "483",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": true,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3428019",
  "year_published": 2012,
  "pm_id": "22281772",
  "article_name": "Toward interoperable bioscience data.",
  "authors": ["Sansone SA", "Rocca-Serra P", "Field D", "Maguire E", "Taylor C", "Hofmann O", "Fang H", "Neumann S", "Tong W", "Amaral-Zettler L", "Begley K", "Booth T", "Bougueleret L", "Burns G", "Chapman B", "Clark T", "Coleman LA", "Copeland J", "Das S", "de Daruvar A", "de Matos P", "Dix I", "Edmunds S", "Evelo CT", "Forster MJ", "Gaudet P", "Gilbert J", "Goble C", "Griffin JL", "Jacob D", "Kleinjans J", "Harland L", "Haug K", "Hermjakob H", "Ho Sui SJ", "Laederach A", "Liang S", "Marshall S", "McGrath A", "Merrill E", "Reilly D", "Roux M", "Shamu CE", "Shang CA", "Steinbeck C", "Trefethen A", "Williams-Jones B", "Wolstencroft K", "Xenarios I", "Hide W"],
  "issue": "2",
  "pp_pages": "121-6",
  "journal_name": "Nature Genetics",
  "comp_tools": [],
  "doi": "10.1038/ng.1054",
  "other_link": null,
  "volume": "44",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": true,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3498356",
  "year_published": 2012,
  "pm_id": "23155465",
  "article_name": "Formalization, annotation and analysis of diverse drug and probe screening assay datasets using the BioAssay Ontology (BAO).",
  "authors": ["Vempati", "UD", "Przydzial MJ", "Chung C", "Abeyruwan S", "Mir A", "Sakurai K", "Visser U", "Lemmon VP", "Sch\u00fcrer SC"],
  "issue": "11",
  "pp_pages": "e49198",
  "journal_name": "PLoS One",
  "comp_tools": [{
    "name": "BAO",
    "url": "http://bioportal.bioontology.org/ontologies/1533"
  }],
  "doi": "10.1371/journal.pone.0049198",
  "other_link": null,
  "volume": "7",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": true,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3270411",
  "year_published": 2012,
  "pm_id": "22284361",
  "article_name": "Discovery of potent and selective covalent inhibitors of JNK.",
  "authors": ["Zhang T", "Inesta-Vaquera F", "Niepel M", "Zhang J", "Ficarro SB", "Machleidt T", "Xie T", "Marto JA", "Kim N", "Sim T", "Laughlin JD", "Park H", "Lograsso PV", "Patricelli M", "Nomanbhoy TK", "Sorger PK", "Alessi DR", "Gray NS"],
  "issue": "1",
  "pp_pages": "140-54",
  "journal_name": "Chemistry and Biology",
  "comp_tools": [],
  "doi": "10.1016/j.chembiol.2011.11.010",
  "other_link": null,
  "volume": "19",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": null,
  "year_published": 2012,
  "pm_id": "22991099",
  "article_name": "High-content single cell analysis on chip using a laser microarray scanner.",
  "authors": ["Zhou J", "Wu Y", "Lee SK", "Fan R"],
  "issue": "23",
  "pp_pages": "5025-33",
  "journal_name": "Lab on a Chip",
  "comp_tools": [],
  "doi": "10.1039/c2lc40309a",
  "other_link": null,
  "volume": "12",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC3105758",
  "year_published": 2011,
  "pm_id": "21516115",
  "article_name": "Adaptive informatics for multifactorial and high-content biological data.",
  "authors": ["Millard BL", "Niepel M", "Menden MP", "Muhlich JL", "Sorger PK"],
  "issue": "6",
  "pp_pages": "487-93",
  "journal_name": "Nature Methods",
  "comp_tools": [{
    "name": "SDCubes",
    "url": "https://github.com/sorgerlab/SDCube_API"
  }],
  "doi": "10.1038/nmeth.1600",
  "other_link": null,
  "volume": "8",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC3465072",
  "year_published": 2011,
  "pm_id": "21900204",
  "article_name": "Crowdsourcing network inference: the dream predictive signaling network challenge.",
  "authors": ["Prill RJ", "Saez-Rodriguez J", "Alexopoulos LG", "Sorger PK", "Stolovitzky G"],
  "issue": "189",
  "pp_pages": "mr7",
  "journal_name": "Science Signaling ",
  "comp_tools": [],
  "doi": "10.1126/scisignal.2002212",
  "other_link": null,
  "volume": "4",
  "assay_development": false,
  "data_analysis": false,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": true,
}, {
  "pmc_id": "PMC4675694",
  "year_published": 2015,
  "pm_id": "26101093",
  "article_name": "Abstraction for data integration: Fusing mammalian molecular, cellular and phenotype big datasets for better knowledge extraction.",
  "authors": ["Rouillard AD", "Wang Z", "Ma’ayan A"],
  "issue": null,
  "pp_pages": "104-19",
  "journal_name": "Computational Biology and Chemistry",
  "comp_tools": [],
  "doi": null,
  "other_link": null,
  "volume": "58",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": true,
}, {
  "pmc_id": "PMC4587398",
  "year_published": 2015,
  "pm_id": "26399630",
  "article_name": "Highly multiplexed imaging of single cells using a high-throughput cyclic immunofluorescence method.",
  "authors": ["Lin JR", "Fallahi-Sichani M", "Sorger PK"],
  "issue": null,
  "pp_pages": "8390",
  "journal_name": "Nature Communications",
  "comp_tools": [{
    "name": "Data exploration website",
    "url": "http://lincs.hms.harvard.edu/lin-natcommun-2015/"
  }],
  "doi": null,
  "other_link": null,
  "volume": "6",
  "assay_development": true,
  "data_analysis": false,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": true,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4737646",
  "year_published": 2015,
  "pm_id": "26848405",
  "article_name": "Principal Angle Enrichment Analysis (PAEA): Dimensionally reduced multivariate gene set enrichment analysis tool.",
  "authors": ["Clark NR", "Szymkiewicz M", "Wang Z", "Monteiro CD", "Jones MR", "Ma’ayan A"],
  "issue": null,
  "pp_pages": "256-262",
  "journal_name": "Proceedings (IEEE Int Conf Bioinformatics Biomed)",
  "comp_tools": [{
    "name": "PAEA",
    "url": "http://amp.pharm.mssm.edu/PAEA/"
  }],
  "doi": null,
  "other_link": null,
  "volume" : null,
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": true,
  "review": false,
}, {
  "pmc_id": "PMC4657038",
  "year_published": 2015,
  "pm_id": "26596901",
  "article_name": "Large-scale computational screening identifies first in class multitarget inhibitor of EGFR kinase and BRD4.",
  "authors": ["Allen BK", "Mehta S", "Ember SW", "Schonbrunn E", "Ayad N", "Schurer SC"],
  "issue": null,
  "pp_pages": "16924",
  "journal_name": "Scientific Reports",
  "comp_tools": [],
  "doi": null,
  "other_link": null,
  "volume": "5",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": true,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": null,
  "year_published": 2016,
  "pm_id": "26821783",
  "article_name": "A three-groups model for high-throughput survival screens.",
  "authors": ["Shaby BA", "Skibinski G", "Ando M", "LaDow ES", "Finkbeiner S"],
  "issue": null,
  "pp_pages": null,
  "journal_name": "Biometrics",
  "comp_tools": [],
  "doi": null,
  "other_link": null,
  "volume": null,
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": null,
  "year_published": 2016,
  "pm_id": null,
  "article_name": "Cell freezing protocol optimized for ATAC-Seq on motor neurons derived from human induced pluripotent stem cells.",
  "authors": ["Milani P", "Escalante-Chong R", "Shelley BC", "Patel-Murray NL", "Xin X", "Adam M", "Mandefro B", "Sareen D", "Svendsen CN", "Fraenkel E"],
  "issue": null,
  "pp_pages": null,
  "journal_name": "bioRxiv",
  "comp_tools": [],
  "doi": "10.1101/036798",
  "other_link": null,
  "volume": null,
  "assay_development": true,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": "PMC4707261",
  "year_published": 2016,
  "pm_id": "26793058",
  "article_name": "Spinal muscular atrophy patient iPSC-derived motor neurons have reduced expression of proteins important in neuronal development.",
  "authors": ["Fuller HR", "Mandefro B", "Shirran SL", "Gross AR", "Kaus AS", "Botting CH", "Morris GE", "Sareen D"],
  "issue": null,
  "pp_pages": "506",
  "journal_name": "Frontiers in Cellular Neuroscience",
  "comp_tools": [],
  "doi": null,
  "other_link": null,
  "volume": "9",
  "assay_development": false,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": null,
  "year_published": 2016,
  "pm_id": "26912667",
  "article_name": "Reduced-representation phosphosignatures measured by quantitative targeted MS capture cellular states and enable large-scale comparison of drug-induced phenotypes.",
  "authors": ["Abelin JG", "Patel J", "Lu X", "Feeney CM", "Fagbami L, et al"],
  "issue": null,
  "pp_pages": null,
  "journal_name": "Molecular and Cellular Proteomics",
  "comp_tools": [],
  "doi": null,
  "other_link": null,
  "volume": null,
  "assay_development": true,
  "data_analysis": true,
  "data_generation": true,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}, {
  "pmc_id": null,
  "year_published": 2016,
  "pm_id": null,
  "article_name": "A posterior probability approach for gene regulatory network inference in genetic perturbation data.",
  "authors": ["Young CW", "Yeung KY", "Raftery AE"],
  "issue": null,
  "pp_pages": null,
  "journal_name": null,
  "comp_tools": [],
  "doi": null,
  "other_link": "http://arxiv.org/abs/1603.04835",
  "volume": null,
  "assay_development": false,
  "data_analysis": true,
  "data_generation": false,
  "data_integration": false,
  "data_standards": false,
  "signature_generation": false,
  "software_development": false,
  "review": false,
}]
