/* eslint max-len:0 */

module.exports = [
  {
    title: 'Biomedical Data Integration Toward Quality Healthcare Delivery',
    presenter_name: 'Qian Zhu, PhD',
    presenter_affiliation: 'University of Maryland, Baltimore County',
    presenter_url: '',
    url: '',
    date: new Date('2015-08-11T06:00:00.000Z'),
  },
  {
    title: 'L1000 Indexing Process',
    presenter_name: 'Amar Koleti',
    presenter_affiliation: 'Schurer Group, University of Miami, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=ncaSK0y36ck',
    date: new Date('2014-10-21T06:00:00.000Z'),
  },
  {
    title: 'The Construction of a Cluster Stack Based on Open Source Technologies',
    presenter_name: 'Matthew Jones',
    presenter_affiliation: 'Ma’ayan Lab, Icahn School of Medicine at Mount Sinai, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=QJPirW-JjQ4',
    date: new Date('2015-06-23T06:00:00.000Z'),
  },
  {
    title: 'L1K++: A Fast Pipeline that Increases the Accuracy of L1000 Gene Expression Data',
    presenter_name: 'Ling-Hong Hung PhD',
    presenter_affiliation: 'Yeung Group, University of Washington, BD2K-LINCS DCIC External Data Science Research Project',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=jcpEagg1iaQ',
    date: new Date('2015-06-15T06:00:00.000Z'),
  },
  {
    title: 'Drug Toxicity Signature Generation Center',
    presenter_name: 'Eric Sobie PhD',
    presenter_affiliation: 'Icahn School of Medicine at Mount Sinai, DToxS',
    presenter_url: 'http://research.mssm.edu/pst/DToxS/index.html',
    url: 'https://www.youtube.com/watch?v=85xfd9YS3vQ',
    date: new Date('2015-06-09T06:00:00.000Z'),
  },
  {
    title: 'Integrative Analysis of Proteomics Data of Multi-Layered Post Translational Modifications Collected from Human Lung Cancer Cell Lines',
    presenter_name: 'Peter Hornbeck PhD, Klarisa Rikova, Mark Grimes PhD, Neil Clark PhD, Nicolas Fernandez PhD',
    presenter_affiliation: 'Cell Signaling Technology and Ma’ayan Lab, BD2K-LINCS DCIC External Data Science Research Project',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=HQxincOIqNM',
    date: new Date('2015-05-02T06:00:00.000Z'),
  },
  {
    title: 'Assessing the Global Dimensionality of LINCS Signatures',
    presenter_name: 'Neil Clark PhD',
    presenter_affiliation: 'Ma’ayan Lab, Icahn School of Medicine at Mount Sinai, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=8s3HYdVlEoM',
    date: new Date('2015-05-05T06:00:00.000Z'),
  },
  {
    title: 'Target Predictions using LINCS Perturbation Data',
    presenter_name: 'Yan Xia',
    presenter_affiliation: 'Bar-Joseph Group, Carnegie Mellon University, BD2K-LINCS DCIC External Data Science Research Project',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=afz36W6G7iE',
    date: new Date('2015-04-21T06:00:00.000Z'),
  },
  {
    title: 'Prediction of Adverse Events for LINCS Drugs using L1000 Gene Expression Data, Cell Morphology Profiles and Chemical Structure Features',
    presenter_name: 'Zichen Wang',
    presenter_affiliation: 'Ma’ayan Lab, Icahn School of Medicine at Mount Sinai, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=EHUAU05O0kQ&list=PL0Bwuj8819U-G9Ob0jIGHp5AtwpCghLV5&index=1',
    date: new Date('2015-04-14T06:00:00.000Z'),
  },
  {
    title: 'Transcriptional Landscape of Drug Response Guides the Design of Specific and Potent Drug Combinations',
    presenter_name: 'Marc Hafner PhD',
    presenter_affiliation: 'Sorger Lab, Harvard Medical School, HMS LINCS',
    presenter_url: 'http://lincs.hms.harvard.edu/',
    url: 'https://www.youtube.com/watch?v=kdKk3jHUR9c&list=UU88h_MIO1LP7Jv52VQ4qKkg',
    date: new Date('2015-03-10T06:00:00.000Z'),
  },
  {
    title: 'Leveraging Experimental Models to Advance Our Understanding of Cancer',
    presenter_name: 'Laura Heiser PhD',
    presenter_affiliation: 'Oregon Health and Science University, MEP LINCS',
    presenter_url: '',
    url: 'https://www.youtube.com/watch?v=9KM7inVCLoc',
    date: new Date('2015-02-24T06:00:00.000Z'),
  },
  {
    title: 'Discussion of Causes for Some Artifacts Observed in L1000 Data',
    presenter_name: 'William Chad Young',
    presenter_affiliation: 'Yeung Group, University of Washington, BD2K-LINCS DCIC External Data Science Research Project',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=d-E_siojRg4',
    date: new Date('2015-02-17T06:00:00.000Z'),
  },
  {
    title: 'Large-scale Integration of Small Molecule-induced Responses in Diverse LINCS Datasets',
    presenter_name: 'Dusica Vidovic PhD',
    presenter_affiliation: 'Schurer Group, University of Miami, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=TKPSqRrtd6I',
    date: new Date('2014-12-16T06:00:00.000Z'),
  },
  {
    title: 'Analysis of Lung Cancers Across Multiple Signaling Spaces to Identify New Disease Drivers and Network Connectivity',
    presenter_name: 'Peter Hornbeck PhD',
    presenter_affiliation: 'Cell Signaling Technology, BD2K-LINCS DCIC External Data Science Research Project',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=mgud2LcCdVY',
    date: new Date('2014-12-09T06:00:00.000Z'),
  },
  {
    title: 'Explaining Artifacts in Level 3 L1000 Data, Benchmarking Perturbation Signatures',
    presenter_name: 'Mario Medvedovic PhD',
    presenter_affiliation: 'University of Cincinnati, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=eEIXm5rpo-E',
    date: new Date('2014-12-02T06:00:00.000Z'),
  },
  {
    title: 'Creating Signatures from the ENCODE Data',
    presenter_name: 'Yan Kou',
    presenter_affiliation: 'Ma’ayan Lab, Icahn School of Medicine at Mount Sinai, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=HjDakxNoFCE',
    date: new Date('2014-11-18T06:00:00.000Z'),
  },
  {
    title: 'Issues in Level 3 L1000 Data',
    presenter_name: 'William Chad Young',
    presenter_affiliation: 'Yeung Group, University of Washington, BD2K-LINCS DCIC External Data Science Research Project',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=-tActS2zkEU',
    date: new Date('2014-11-18T06:00:00.000Z'),
  },
  {
    title: 'LINCS L1000 Analysis with the Characteristic Direction Method',
    presenter_name: 'Qiaonan Duan',
    presenter_affiliation: 'Ma’ayan Lab, Icahn School of Medicine at Mount Sinai, BD2K-LINCS DCIC',
    presenter_url: 'http://www.lincs-dcic.org/#/',
    url: 'https://www.youtube.com/watch?v=6rkqn6sqmBI',
    date: new Date('2014-10-28T06:00:00.000Z'),
  },
  {
    title: 'Drug Repositioning by Integrating Target Information through a Heterogeneous Network Model',
    presenter_name: 'Jing Li, PhD',
    presenter_affiliation: 'Case Western Reserve University',
    presenter_url: 'https://sites.google.com/a/case.edu/jingli/',
    url: '',
    date: new Date('2015-08-25T06:00:00.000Z'),
  },
  {
    title: 'Using Machine Learning to Identify Aberrant Pathway Activity',
    presenter_name: 'Stephen Piccolo, PhD',
    presenter_affiliation: 'Brigham Young University',
    presenter_url: 'https://piccolo.byu.edu',
    url: '',
    date: new Date('2015-09-08T06:00:00.000Z'),
  },
];
